spring:
  application:
    name: auth-service
  profiles:
    active: dev
server:
  port: 10323

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

jwt:
  secret: Ny0pm2CWIAST07ElsTAVZgCqJKJd2bE9lpKyewuOhyyKoBApt1Ny0pm2CWIAST07ElsTAVZgCqJKJd2bE9lpKyewuOhyyKoBApt1
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000
  header-string: Authorization
  token-prefix: Bearer
