spring:
  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10322/eureka
  instance:
    prefer-ip-address: true

payco:
  client-id: 3RDPyQi9kr4B7gUWkZISpaH
  client-secret: GJbdDfh8VXvAO30gZDv1UuxZ
  redirect-uri: http://test.com:10320/auth/login/payco/callback
  authorization-uri: https://id.payco.com/oauth2.0/authorize
  token-uri: https://id.payco.com/oauth2.0/token
  user-info-uri: https://apis-payco.krp.toastoven.net/payco/friends/find_member_v2.json
  gateway-uri: http://test.com:10320

jwt:
  cookie:
    secure: false
    same-site: Lax