spring:
  data:
    redis:
      host: s4.java21.net
      port: 6379
      password: "*N2vya7H@muDTwdNMR!"
      database: 305

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://dodream.shop:10322/eureka
  instance:
    prefer-ip-address: false
    hostname: dodream.shop